changelog:
  categories:
    - title: Features
      labels:
        - feature
        - feat
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: CI
      labels:
        - ci
        - chore-ci
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - wontfix
